version: '3'


services:

  http:
    build:
      context: ./http
      dockerfile: Dockerfile
    command: ./http
    container_name: p2p_http
    network_mode: host
    ports:
      - "8000:8000"
      - "50052:50052"

  lemmatizer:
    build:
      context: ./lemmatizer
      dockerfile: Dockerfile
    command: python3 main.py
    container_name: p2p_lemmatizer
    network_mode: host
    ports:
      - "50051:50051"
  
  network:
    build:
      context: ./network
      dockerfile: Dockerfile
    command: ./network
    container_name: p2p_network
    volumes:
      - data_volume:/home/app/network/pkg/p2p/data
    network_mode: host
    ports:
      - "50051:50051"
      - "50052:50052"
      - "2000-4000"

volumes:
  data_volume:
