// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: lemmatizer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LemmatizerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *LemmatizerRequest) Reset() {
	*x = LemmatizerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lemmatizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LemmatizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmatizerRequest) ProtoMessage() {}

func (x *LemmatizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lemmatizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmatizerRequest.ProtoReflect.Descriptor instead.
func (*LemmatizerRequest) Descriptor() ([]byte, []int) {
	return file_lemmatizer_proto_rawDescGZIP(), []int{0}
}

func (x *LemmatizerRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LemmatizedWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sentence string `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`
	Word     string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Id       int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LemmatizedWord) Reset() {
	*x = LemmatizedWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lemmatizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LemmatizedWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmatizedWord) ProtoMessage() {}

func (x *LemmatizedWord) ProtoReflect() protoreflect.Message {
	mi := &file_lemmatizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmatizedWord.ProtoReflect.Descriptor instead.
func (*LemmatizedWord) Descriptor() ([]byte, []int) {
	return file_lemmatizer_proto_rawDescGZIP(), []int{1}
}

func (x *LemmatizedWord) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

func (x *LemmatizedWord) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *LemmatizedWord) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LemmatizerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []*LemmatizedWord `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *LemmatizerResponse) Reset() {
	*x = LemmatizerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lemmatizer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LemmatizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmatizerResponse) ProtoMessage() {}

func (x *LemmatizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lemmatizer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmatizerResponse.ProtoReflect.Descriptor instead.
func (*LemmatizerResponse) Descriptor() ([]byte, []int) {
	return file_lemmatizer_proto_rawDescGZIP(), []int{2}
}

func (x *LemmatizerResponse) GetWords() []*LemmatizedWord {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_lemmatizer_proto protoreflect.FileDescriptor

var file_lemmatizer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x65, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x70, 0x32, 0x70, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x65, 0x6d, 0x6d, 0x61,
	0x74, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x50, 0x0a, 0x0e, 0x4c, 0x65, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x64, 0x57, 0x6f,
	0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x3f, 0x0a, 0x12, 0x4c, 0x65, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x4c, 0x65,
	0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x32, 0x4b, 0x0a, 0x0b, 0x4c, 0x65, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65,
	0x72, 0x73, 0x12, 0x3c, 0x0a, 0x09, 0x4c, 0x65, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x12,
	0x16, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x4c, 0x65, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x4c, 0x65,
	0x6d, 0x6d, 0x61, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lemmatizer_proto_rawDescOnce sync.Once
	file_lemmatizer_proto_rawDescData = file_lemmatizer_proto_rawDesc
)

func file_lemmatizer_proto_rawDescGZIP() []byte {
	file_lemmatizer_proto_rawDescOnce.Do(func() {
		file_lemmatizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_lemmatizer_proto_rawDescData)
	})
	return file_lemmatizer_proto_rawDescData
}

var file_lemmatizer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lemmatizer_proto_goTypes = []interface{}{
	(*LemmatizerRequest)(nil),  // 0: p2p.LemmatizerRequest
	(*LemmatizedWord)(nil),     // 1: p2p.LemmatizedWord
	(*LemmatizerResponse)(nil), // 2: p2p.LemmatizerResponse
}
var file_lemmatizer_proto_depIdxs = []int32{
	1, // 0: p2p.LemmatizerResponse.words:type_name -> p2p.LemmatizedWord
	0, // 1: p2p.Lemmatizers.Lemmatize:input_type -> p2p.LemmatizerRequest
	2, // 2: p2p.Lemmatizers.Lemmatize:output_type -> p2p.LemmatizerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lemmatizer_proto_init() }
func file_lemmatizer_proto_init() {
	if File_lemmatizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lemmatizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LemmatizerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lemmatizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LemmatizedWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lemmatizer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LemmatizerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lemmatizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lemmatizer_proto_goTypes,
		DependencyIndexes: file_lemmatizer_proto_depIdxs,
		MessageInfos:      file_lemmatizer_proto_msgTypes,
	}.Build()
	File_lemmatizer_proto = out.File
	file_lemmatizer_proto_rawDesc = nil
	file_lemmatizer_proto_goTypes = nil
	file_lemmatizer_proto_depIdxs = nil
}
