// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: lemmatizer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LemmatizersClient is the client API for Lemmatizers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LemmatizersClient interface {
	Lemmatize(ctx context.Context, in *LemmatizerRequest, opts ...grpc.CallOption) (*LemmatizerResponse, error)
}

type lemmatizersClient struct {
	cc grpc.ClientConnInterface
}

func NewLemmatizersClient(cc grpc.ClientConnInterface) LemmatizersClient {
	return &lemmatizersClient{cc}
}

func (c *lemmatizersClient) Lemmatize(ctx context.Context, in *LemmatizerRequest, opts ...grpc.CallOption) (*LemmatizerResponse, error) {
	out := new(LemmatizerResponse)
	err := c.cc.Invoke(ctx, "/p2p.Lemmatizers/Lemmatize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LemmatizersServer is the server API for Lemmatizers service.
// All implementations must embed UnimplementedLemmatizersServer
// for forward compatibility
type LemmatizersServer interface {
	Lemmatize(context.Context, *LemmatizerRequest) (*LemmatizerResponse, error)
	mustEmbedUnimplementedLemmatizersServer()
}

// UnimplementedLemmatizersServer must be embedded to have forward compatible implementations.
type UnimplementedLemmatizersServer struct {
}

func (UnimplementedLemmatizersServer) Lemmatize(context.Context, *LemmatizerRequest) (*LemmatizerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lemmatize not implemented")
}
func (UnimplementedLemmatizersServer) mustEmbedUnimplementedLemmatizersServer() {}

// UnsafeLemmatizersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LemmatizersServer will
// result in compilation errors.
type UnsafeLemmatizersServer interface {
	mustEmbedUnimplementedLemmatizersServer()
}

func RegisterLemmatizersServer(s grpc.ServiceRegistrar, srv LemmatizersServer) {
	s.RegisterService(&Lemmatizers_ServiceDesc, srv)
}

func _Lemmatizers_Lemmatize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LemmatizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LemmatizersServer).Lemmatize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p.Lemmatizers/Lemmatize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LemmatizersServer).Lemmatize(ctx, req.(*LemmatizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lemmatizers_ServiceDesc is the grpc.ServiceDesc for Lemmatizers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lemmatizers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.Lemmatizers",
	HandlerType: (*LemmatizersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lemmatize",
			Handler:    _Lemmatizers_Lemmatize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lemmatizer.proto",
}
