name: network-tests
on:
  push:
    paths:
      - .github/workflows/network-tests.yml
      - network/**

defaults:
  run:
    working-directory: ./network

jobs:
  network-tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: make test